version: '2'

volumes:
  pg_data:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "1432:5432"
    restart: always

  go:
    image: golang:1.8
    command: go run app/main.go
    working_dir: /go/src/github.com/jirfag/beepcar-telegram-bot
    volumes:
      - ./:/go/src/github.com/jirfag/beepcar-telegram-bot
    depends_on:
      - db
    environment:
      - GO_ENV=production
    ports:
      - "127.0.0.1:3030:3030"
    restart: always
